# Generated by Django 3.1.4 on 2021-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunlink', models.CharField(max_length=500)),
                ('stokkod', models.CharField(max_length=20)),
                ('birim', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('stok', models.IntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ozellik', models.TextField(blank=True, null=True)),
                ('imglink', models.CharField(blank=True, max_length=500, null=True)),
                ('anakategori', models.CharField(max_length=50)),
                ('altkategori', models.CharField(max_length=50)),
                ('sonkategori', models.CharField(max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('checkCount', models.IntegerField(default=0)),
                ('stokislem', models.CharField(blank=True, max_length=20, null=True)),
                ('fiyatislem', models.CharField(blank=True, max_length=20, null=True)),
                ('kcreated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='seleniumpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
